# **I. Data Types and Constants**

**Data Types**

TensorFlow supports various data types, each serving a specific purpose. Let's delve into some of the commonly used ones:

In [ ]:
import tensorflow as tf

# Floating-point types
float_tensor = tf.constant(3.14, dtype=tf.float32)
double_tensor = tf.constant(3.14, dtype=tf.float64)

# Integer types
int_tensor = tf.constant(10, dtype=tf.int32)

# Boolean types
bool_tensor = tf.constant(True, dtype=tf.bool)

# String types
string_tensor = tf.constant("Hello Word!", dtype=tf.string)

**Constants**

Constants are unchangeable tensors and are often used to represent fixed values:

In [ ]:
# Creating constants
const_tensor = tf.constant([1, 2, 3])

# Operations with constants
result = const_tensor * 5

# **II. Basic functions**

TensorFlow provides a wide range of basic functions for constructing and manipulating tensors, performing mathematical operations, and building machine learning models. Here are some fundamental functions in TensorFlow:

**tf.add: Element-wise addition.**

Element-wise addition: Adds corresponding elements of two tensors, creating a new tensor with the results.

In [ ]:
# Create two tensors
tensor_a = tf.constant([1, 2, 3], dtype=tf.float32)
tensor_b = tf.constant([4, 5, 6], dtype=tf.float32)

In [ ]:
# Element-wise addition
add_result = tf.add(tensor_a, tensor_b)

print("Element-wise addition result:", add_result.numpy())


Element-wise addition result: [5. 7. 9.]


**tf.subtract: Element-wise subtraction.**

Element-wise subtraction: Subtracts corresponding elements of two tensors, creating a new tensor with the results.

In [ ]:
# Element-wise subtraction
subtract_result = tf.subtract(tensor_a, tensor_b)

print("Element-wise subtraction result:", subtract_result.numpy())

Element-wise subtraction result: [-3. -3. -3.]


**tf.multiply: Element-wise multiplication.**

Element-wise multiplication: Multiplies corresponding elements of two tensors, creating a new tensor with the results.

In [ ]:
# Element-wise multiplication
multiply_result = tf.multiply(tensor_a, tensor_b)

print("Element-wise multiplication result:", multiply_result.numpy())

Element-wise multiplication result: [ 4. 10. 18.]


**tf.divide: Element-wise division.**

Element-wise division: Divides corresponding elements of two tensors, creating a new tensor with the results.

In [ ]:
# Element-wise division
divide_result = tf.divide(tensor_a, tensor_b)

print("Element-wise division result:", divide_result.numpy())

Element-wise division result: [0.25 0.4  0.5 ]


**tf.square: Element-wise square.**

Element-wise square: Computes the square of each element in the tensor, creating a new tensor with the squared values.

In [ ]:
# Element-wise square
square_result = tf.square(tensor_a)

print("Element-wise square result:", square_result.numpy())

Element-wise square result: [1. 4. 9.]


**tf.sqrt: Element-wise square root.**

Element-wise square root: Computes the square root of each element in the tensor, creating a new tensor with the square root values.


In [ ]:
# Element-wise square root
sqrt_result = tf.sqrt(tensor_a)

print("Element-wise square root result:", sqrt_result.numpy())

Element-wise square root result: [1.        1.4142135 1.7320508]


**tf.reduce_sum: Computes the sum of elements along specified dimensions.**

In [ ]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Reduce Sum along axis 1 (columns)
sum_result = tf.reduce_sum(tensor, axis=1)

print("Reduce Sum result:", sum_result.numpy())

Reduce Sum result: [ 6 15]


We can use the same same approach using: **tf.reduce_mean**, **tf.reduce_max** and **tf.reduce_min**.

**tf.squeeze and tf.unsqueeze**

tf.squeeze and tf.unsqueeze are functions used to manipulate the dimensions of a tensor by removing or adding dimensions with size 1, respectively.

In [ ]:
# Example with tf.squeeze
tensor_a = tf.constant([[[1], [2], [3]]])  # Shape: (1, 3, 1)
squeezed_tensor = tf.squeeze(tensor_a, axis=0) # Shape: (3, 1)
squeezed_tensor = tf.squeeze(tensor_a)       # Shape: (3,)

In [ ]:
# Example with tf.unsqueeze
tensor_b = tf.constant([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
unsqueezed_tensor = tf.unsqueeze(tensor_b, axis=-1)  # Shape: (2, 3, 1)
unsqueezed_tensor = tensor_b[:, :, tf.newaxis] # Shape: (2, 3, 1)

**tf.tile**

tf.tile is a TensorFlow function that is used to construct a new tensor by replicating the input tensor. It replicates the data along specified dimensions, creating a larger tensor with repeated copies of the original data.

In [1]:
# Example with tf.tile
tensor_a = tf.constant([[1, 2], [3, 4]])  # Shape: (2, 2)

# Tile the tensor along each dimension
tiled_tensor = tf.tile(tensor_a, multiples=[2, 3])  # Shape: (4, 6)

# Display the original and tiled tensors
print("Original Tensor:")
print(tensor_a.numpy())
print("\nTiled Tensor:")
print(tiled_tensor.numpy())

Original Tensor:
[[1 2]
 [3 4]]

Tiled Tensor:
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


**tf.gather**

tf.gather is a TensorFlow function that is used to gather slices from a tensor along a specified axis. It allows you to extract specific elements or sub-tensors from a larger tensor based on the provided indices.

In [3]:
# Example tensor
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])

# Indices to gather
indices = tf.constant([0, 2])

# Gather values along axis 0
result = tf.gather(tensor, indices, axis=0)

print(result.numpy())

[[1 2]
 [5 6]]


In [4]:
# Example tensor
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])

# Indices to gather62.48%
indices = tf.constant([0, 1])

# Gather values along axis 1
result = tf.gather(tensor, indices, axis=1)

result.numpy()


array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

**tf.nn.embedding_lookup**

tf.nn.embedding_lookup is a TensorFlow function used for performing embedding lookups. Embeddings are used to map discrete indices (such as word indices in natural language processing) to continuous vector representations. The tf.nn.embedding_lookup function facilitates this process by efficiently extracting the embeddings corresponding to a set of indices.

In [5]:
# Example with tf.nn.embedding_lookup
embedding_matrix = tf.constant([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])  # Shape: (3, 3)
indices_to_lookup = tf.constant([0, 2])  # Indices to look up

# Perform embedding lookup
embeddings = tf.nn.embedding_lookup(embedding_matrix, indices_to_lookup)

# Display the original embedding matrix and the looked-up embeddings
print("Original Embedding Matrix:")
print(embedding_matrix.numpy())
print("\nLooked-up Embeddings:")
print(embeddings.numpy())


Original Embedding Matrix:
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]

Looked-up Embeddings:
[[0.1 0.2 0.3]
 [0.7 0.8 0.9]]


**tf.not_equal**

tf.not_equal is a TensorFlow function that performs element-wise inequality comparison between two tensors. It returns a tensor of the same shape as the input tensors, where each element is 1 if the corresponding elements are not equal and 0 if they are equal.

In [6]:
# Example with tf.not_equal
tensor_a = tf.constant([1, 2, 3, 4])
tensor_b = tf.constant([2, 2, 3, 4])

# Perform element-wise inequality comparison
not_equal_result = tf.not_equal(tensor_a, tensor_b)

# Display the original tensors and the result of the comparison
print("Tensor A:", tensor_a.numpy())
print("Tensor B:", tensor_b.numpy())
print("Not Equal Result:", not_equal_result.numpy())

Tensor A: [1 2 3 4]
Tensor B: [2 2 3 4]
Not Equal Result: [ True False False False]


**tf.logical_and**

tf.logical_and is a TensorFlow function that performs element-wise logical AND operation between two boolean tensors. It returns a new boolean tensor of the same shape as the input tensors, where each element is True if the corresponding elements in both input tensors are True, and False otherwise. We can use in the same way **tf.logical_or** and **tf.logical_xor**, etc.

In [7]:
# Example with tf.logical_and
tensor_a = tf.constant([True, True, False, False], dtype=tf.bool)
tensor_b = tf.constant([True, False, True, False], dtype=tf.bool)

# Perform element-wise logical AND operation
logical_and_result = tf.logical_and(tensor_a, tensor_b)

# Display the original boolean tensors and the result of the AND operation
print("Tensor A:", tensor_a.numpy())
print("Tensor B:", tensor_b.numpy())
print("Logical AND Result:", logical_and_result.numpy())

Tensor A: [ True  True False False]
Tensor B: [ True False  True False]
Logical AND Result: [ True False False False]


**tf.cast**

tf.cast is a TensorFlow function used to cast a tensor to a new data type. It allows you to change the data type of a tensor to another data type, possibly of lower or higher precision.

In [8]:
# Example with tf.cast
tensor_a = tf.constant([1.2, 2.5, 3.8], dtype=tf.float32)

# Cast the tensor to int32 data type
casted_tensor = tf.cast(tensor_a, dtype=tf.int32)

# Display the original tensor and the casted tensor
print("Original Tensor (float32):", tensor_a.numpy())
print("Casted Tensor (int32):", casted_tensor.numpy())

Original Tensor (float32): [1.2 2.5 3.8]
Casted Tensor (int32): [1 2 3]


In [9]:
# Example with tf.cast
tensor_a = tf.constant([True, False, True], dtype=tf.bool)

# Cast the tensor to int32 data type
casted_tensor = tf.cast(tensor_a, dtype=tf.int32)

# Display the original tensor and the casted tensor
print("Original Tensor (float32):", tensor_a.numpy())
print("Casted Tensor (int32):", casted_tensor.numpy())

Original Tensor (float32): [ True False  True]
Casted Tensor (int32): [1 0 1]


**tf.einsum**

tf.einsum is a TensorFlow function that provides a flexible and concise way to specify operations involving tensors using Einstein summation convention. This convention allows you to define a wide range of linear algebraic operations, including matrix multiplication, contraction, and other element-wise operations.

In [10]:
# Example with tf.einsum
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication using einsum
result = tf.einsum('ij,jk->ik', tensor_a, tensor_b)

# Display the original tensors and the result of the einsum operation
print("Tensor A:")
print(tensor_a.numpy())
print("\nTensor B:")
print(tensor_b.numpy())
print("\nResult of einsum operation:")
print(result.numpy())

Tensor A:
[[1 2]
 [3 4]]

Tensor B:
[[5 6]
 [7 8]]

Result of einsum operation:
[[19 22]
 [43 50]]


# **III. Tensorflow dataset**

**tf.data** is a module in TensorFlow that provides a set of tools for building efficient and scalable input pipelines for machine learning models. It's designed to handle large datasets and optimize data loading and preprocessing.

## **1. tf.data.Dataset**

**Dataset Creation:** The tf.data.Dataset API is used to represent a sequence of data elements. It can be created from various data sources such as NumPy arrays, TensorFlow tensors, text files, CSV files, or any custom data source.

In [13]:
import tensorflow as tf

# Create a dataset from a list
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
print(dataset)

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>


In [38]:
# Example in supervised learning
X = tf.random.normal((10, 5))
y = tf.random.normal((10, 1))
dataset = tf.data.Dataset.from_tensor_slices((X, y))
print(dataset)

<_TensorSliceDataset element_spec=(TensorSpec(shape=(5,), dtype=tf.float32, name=None), TensorSpec(shape=(1,), dtype=tf.float32, name=None))>


**Transformation:** You can apply various transformations to a dataset, such as map, filter, and batch, to preprocess and shape the data.

In [39]:
# Apply transformations
def filter_condition(x, y):
    return tf.reduce_sum(x) > 0

dataset = dataset.map(lambda x, y: (x * 2, y)).filter(filter_condition).batch(2)
print(dataset)

<_BatchDataset element_spec=(TensorSpec(shape=(None, 5), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


## **2. Input Pipeline Optimization**

**Parallel Loading:** tf.data can parallelize data loading, enabling faster data ingestion from storage.

In [ ]:
import tensorflow as tf

def parse_function(serialized_example):
    # Define the feature description
    feature_description = {
        'feature1': tf.io.FixedLenFeature([], tf.int64),
        'feature2': tf.io.FixedLenFeature([], tf.float32),
        'label': tf.io.FixedLenFeature([], tf.int64),
    }

    # Parse the example
    example = tf.io.parse_single_example(serialized_example, feature_description)

    # Extract features and label
    feature1 = example['feature1']
    feature2 = example['feature2']
    label = example['label']

    return {'feature1': feature1, 'feature2': feature2}, label

# Parallel loading from multiple files
files = ["file1.tfrecord", "file2.tfrecord", "file3.tfrecord"]
dataset = tf.data.TFRecordDataset(files).map(parse_function)

**Prefetching:** The prefetch transformation allows the data loader to asynchronously fetch batches while the model is training on the current batch

In [ ]:
# Prefetching batches
dataset = dataset.prefetch(buffer_size=tf.data.AUTOTUNE)

## **3. Iterator API**

**Iterators:** You can use iterators to iterate over the elements of a dataset.

In [40]:
# Create a dataset from a list: drop_remainder remove the rest of dataset if it is lower than the size of batch
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5]).batch(2, drop_remainder=True)

# Create an iterator
iterator = iter(dataset)

# Get the next batch
batch = iterator.get_next()
print(batch)

tf.Tensor([1 2], shape=(2,), dtype=int32)


## **Conclusion**

The tf.data module is a powerful tool for efficiently handling and preprocessing data for machine learning models. It allows for a declarative and efficient specification of data pipelines, which is crucial for training models on large datasets.